### ISSUE TITLE
Addition Any.ValueBetween<DateTime, DateTime>(DateTime min, DateTime max) would be great

### ISSUE THREAD

**Issue by RufusJWB** [ymotton/EntroTester#1]
Could be something like:

            IGenerator<long> generator = Any.ValueBetween(minDate.Ticks, maxDate.Ticks);
            if (generator == null)
            {
                throw new Exception("Generator is null");
            }

            long resultTicks = generator.Next(new Random());
            return new DateTime(resultTicks);

**Comment by ymotton** [comment]
Hi, thanks for the feedback. Will take a look at it tonight.

**Comment by ymotton** [comment]
@RufusJWB the overload has been added and a new version(1.1.3) of the package was published.  
I also accept pull requests, so don't hesitate if there's anything else.

Thanks again for the feedback.
