### ISSUE TITLE
netstandard support

### ISSUE THREAD

**Issue by brentboden1** [ymotton/EntroTester#2]
Dear,

Are there any plans to add support for .netstandard / .netcore applications ?

Kind regards,
Brent

**Comment by ymotton** [comment]
Hi Brent,

I'll look into this on the weekend and get back to you before Monday.

**Comment by ymotton** [comment]
Hi Brent,

I have updated EntroBuilder and EntroTester to target netstandard 1.6 as this was most aligned with the codebase and required minimal work.

Hope this works for you.


Kr, Yannick

**Comment by brentboden1** [comment]
Hi Yanninck,

Thanks for the quick response.

Kr, Brent
