### ISSUE TITLE
Add support for user-defined interfaces generation

### ISSUE THREAD

**Issue by brentboden1** [ymotton/EntroTester#3]
Hi Yannick,

When we upgrade to the newest version of entrobuilder we ran into problems when building a builder.
I included a stacktrace from where it went wrong.
![image](https://user-images.githubusercontent.com/5500796/61614358-cc400c00-ac63-11e9-929c-c902aefb288a.png)

Is there anything I'm doing wrong here ?

Kr, Brent

**Comment by ymotton** [comment]
Hi Brent,

It might be a case we don't have an explicit test for yet.
Any chance you can provide me with a PR for the failing test?


Kr, Yannick

**Comment by ymotton** [comment]
Hi Brent,

I might have found the issue. 
Keep you posted on a patch.

Kr, Yannick

**Comment by ymotton** [comment]
Hi Brent,

Somewhere in testing the netstandard package old assemblies where used that gave the green-light when in fact it was very much red. I added an additional test runner for the core use-case.

Patch versions of builder (1.2.1) and tester (1.4.1) have been deployed that fix the issue.


Kr, Yannick

**Comment by brentboden1** [comment]
Hi Yannick,

Unfortunately my issue is not solved by this.
But I found the issue I have, it has something to do wit the interface handling of the code.
When an interface type gets to the typecontext it gets resolved as IsAbstract, and it gets not handled.
So it throws the not supported exception.

Kr Brent.

P.s. I included a test as code, cause i dont know how to make a PR.

    [TestClass]
    public class GenericBuilderTests
    {
        private readonly Builder<ImGoingToFail> _builder = Builder.Create<ImGoingToFail>();

        [TestMethod]
        public void CreateBuilder()
        {
            Assert.IsTrue(_builder != null);
        }

        [TestMethod]
        public void BuildBuilder()
        {
            var b = Builder.Build<ImGoingToFail>();

            Assert.IsTrue(b != null);
        }
    }

    public class ImGoingToFail
    {
        /*This is failing*/
        public IGonnaFail GonnaFail { get; set; }
    }

    public interface IGonnaFail
    {
        int Id { get; set; }
    }

**Comment by brentboden1** [comment]
Hi Yannick,

I have kinda found and solved the issue.

I have added this code above the "context.isClass" section.
`            else if (context.IsInterface)
            {
                var asm = type.GetTypeInfo().Assembly;
                var implementation = asm.ExportedTypes.Where(t => t.ImplementsInterface(type)).FirstOrDefault();
                if (implementation == null) return null;

                instance = Activator.CreateInstance(implementation, true);
            } 
            else if (context.IsClass)`

And also added this to the TypeContext class.
`
                IsInterface = type.IsInterface();`

**Comment by ymotton** [comment]
Hi Brent,


I see what you're trying to do here.  You have a user-defined interface and would like the builder to generate an instance of a class that implements that interface. 

While the solution you have suggested could be a fallback, there are some drawbacks.
For one, this assumes there is an exported type that implements the interface (which makes sense typically, but isn't strictly required), that the implementation can be instantiated through a parameterless constructor, and that the first type you find is the implementation you need.
These might be sensible defaults in your context, but cannot be generally assumed.

Another approach could be to generate a dynamic proxy ( http://www.castleproject.org/projects/dynamicproxy/ ) which does not have the drawbacks mentioned above, but might have its own drawbacks.

The current idiomatic way of providing an implementation for this case specifically is by using `Builder<T>.For<TInterface>(new ConcreteImplementationOfInterfaceGenerator())`.
Sadly this requires the developer to manually provide an instance of the concrete class implementing `TInterface`.

I could add an overload `Builder<T>.For<TInterface, TImplementation>()` that allows to define the implementation mapping for interfaces, similarly to how you would register service implementations on a DI container, while still having `Builder<T>` generate the concrete class instance.

Does that sound workable for you?


Kr, Yannick

**Comment by brentboden1** [comment]
Hi Yannick,

That's true, this would only solve my case.
That overload method would be very helpful.

Kr, Brent

**Comment by ymotton** [comment]
@brentboden1 I released EntroBuilder 1.3 that includes the extra `For<TInterface, TImplementation>()` overload.

**Comment by ymotton** [comment]
@brentboden1 I added a fallback generator that can be configured to do what you were doing (convention based implementation selection). Version 1.4 contains those features.

See https://github.com/ymotton/EntroTester README at the bottom for more info.
